---
binpath:
  linux:
    inkscape: ''
  osx:
    inkscape: /Applications/Inkscape.app/Contents/Resources/bin/inkscape
  win64:
    inkscape: ''
legal publisher:
  american legal:
    origin: http://www.amlegal.com/code-library/
  code publishing:
    origin: https://www.codebook.com/listing
  coded systems:
    origin: http://www.codedsystems.com/codelibrary.html
  conway greene:
    origin: http://www.conwaygreene.com/municipalCodes.htm
  franklin legal:
    origin: http://www.franklinlegal.net/search-codes
  general code:
    origin: x
  municode:
    origin: https://www.municode.com/library/
  quality code:
    origin: http://www.qcode.us/codes.htm
  sterling codifers:
    origin: http://www.sterlingcodifiers.com/municipality.php
north america:
  us:
    supreme court:
      default_destination: 'mnt/Linkstation/Literature/3xx - Social Sciences/344 - Common law, primary materials/73 - United States/072 - Law Reports (modern)'
      default_rename: '"%s",$original_filename'
      origin: https://www.supremecourt.gov/opinions/boundvolumes.aspx
    texas:
      tac:
        origin: http://texreg.sos.state.tx.us/public/readtac$ext.viewtac
        title_size: ~
