north america:
  us:
    texas:
      tac:
        origin:     "http://texreg.sos.state.tx.us/public/readtac$ext.viewtac"
        title_size:
binpath:
  osx:
    inkscape: "/Applications/Inkscape.app/Contents/Resources/bin/inkscape"
  win64:
    inkscape: ""
  linux:
    inkscape: ""